OPENAI_API_KEY = "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"  # Replace with your real key

